export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Artwork } from './Artwork'
export { default as SingleProduct } from './SingleProduct'
export { default as Category } from './Category'