export const ActionTypes = {
    GET_TOKEN: 'GET_TOKEN',
    GET_TOKEN_FAIL: 'GET_TOKEN_FAIL',
    GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

    REGISTER: 'REGISTER',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    LOGIN: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT: 'LOGOUT',

    GET_USER: 'GET_USER',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',

    FETCH_ARTWORK: 'FETCH_ARTWORK',
    FETCH_ARTWORK_FAIL: 'FETCH_ARTWORK_FAIL',
    FETCH_ARTWORK_SUCCESS: 'FETCH_ARTWORK_SUCCESS',

    DUPLICATION_CHECK_EMAIL: 'DUPLICATION_CHECK_EMAIL',
    DUPLICATION_CHECK_EMAIL_FAIL: 'DUPLICATION_CHECK_EMAIL_FAIL',
    DUPLICATION_CHECK_EMAIL_SUCCESS: 'DUPLICATION_CHECK_EMAIL_SUCCESS',

    DUPLICATION_CHECK_NICKNAME: 'DUPLICATION_CHECK_NICKNAME',
    DUPLICATION_CHECK_NICKNAME_FAIL: 'DUPLICATION_CHECK_NICKNAME_FAIL',
    DUPLICATION_CHECK_NICKNAME_SUCCESS: 'DUPLICATION_CHECK_NICKNAME_SUCCESS'
};

export const Errors = {
    UnknownError: "Unknown error!"
};