export const ActionTypes = {
    GET_TOKEN: 'GET_TOKEN',
    GET_TOKEN_FAIL: 'GET_TOKEN_FAIL',
    GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

    REGISTER: 'REGISTER',
    REGISTER_FAIL: 'REGISTER_FAIL',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',

    LOGIN: 'LOGIN',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    LOGOUT: 'LOGOUT',

    GET_USER: 'GET_USER',
    GET_USER_FAIL: 'GET_USER_FAIL',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',

    GET_CART: 'GET_CART',
    GET_CART_FAIL: 'GET_CART_FAIL',
    GET_CART_SUCCESS: 'GET_CART_SUCCESS',
    
    FETCH_ARTWORK: 'FETCH_ARTWORK',
    FETCH_ARTWORK_FAIL: 'FETCH_ARTWORK_FAIL',
    FETCH_ARTWORK_SUCCESS: 'FETCH_ARTWORK_SUCCESS',

    TOGGLE_CART_ITEM: 'TOGGLE_CART_ITEM',
    CALC_CART_PRICE: 'CALC_CART_PRICE',
    
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    DELETE_CART_ITEM_FAIL: 'DELETE_CART_ITEM_FAIL',
    DELETE_CART_ITEM_SUCCESS: 'DELETE_CART_ITEM_SUCCESS'


};

export const Errors = {
    UnknownError: "Unknown error!"
};